#pragma once

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_SPECIAL 
#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_NO_SETUP 
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
// #define CAPS_WORD_INVERT_ON_SHIFT
#define CAPS_WORD_IDLE_TIMEOUT 1500
#define TAPPING_TOGGLE 2
// #define LED_NUM_LOCK_PIN 13